### ISSUE TITLE
JavaScript errors in SS4 with WorkflowEmbargoExpiryExtension

### ISSUE THREAD

**Issue by nathancox** [symbiote/silverstripe-advancedworkflow#377] opened 2018-11-14 01:43 UTC
I initially ran in to this on a CWP 2 upgrade but get the same problems on a fresh install of SS 4.2 and AdvancedWorkflow 5.1.0.

When WorkflowEmbargoExpiryExtension is added to SiteTree it adds the DateTime fields under "Publishing Schedule" but they generate javascript errors in the console.  Opening the edit form produces

```
Uncaught TypeError: Cannot set property 'parseDateTime' of undefined
    at jquery-ui-timepicker-addon.js?m=1542158141:973
    at jquery-ui-timepicker-addon.js?m=1542158141:1882
```

And clicking on one of the DateTime fields give me

```
Uncaught TypeError: Cannot read property '_newInst' of undefined
    at HTMLInputElement.<anonymous> (jquery-ui-timepicker-addon.js?m=1542158141:964)
    at Function.each (eval at e.exports (vendor.js?m=1535060542:1), <anonymous>:660:20)
    at init.each (eval at e.exports (vendor.js?m=1535060542:1), <anonymous>:271:17)
    at init.datetimepicker (jquery-ui-timepicker-addon.js?m=1542158141:962)
    at HTMLInputElement.<anonymous> (jquery-ui-timepicker-addon.js?m=1542158141:941)
    at Function.each (eval at e.exports (vendor.js?m=1535060542:1), <anonymous>:660:20)
    at init.each (eval at e.exports (vendor.js?m=1535060542:1), <anonymous>:271:17)
    at init.timepicker (jquery-ui-timepicker-addon.js?m=1542158141:940)
    at init.onclick (advancedworkflow.js?m=1542158140:1)
    at s (vendor.js?m=1535060542:1)
```
Embargo dates aren't saved when I try to save the page although I don't know if that's related or not.

Any guidance would be much appreciated!

**Comment by robbieaverill** [comment] 2018-11-14 08:06
Hi @nathancox, thanks for raising this issue. The jQuery UI date and time pickers were used in SilverStripe 3, but in SilverStripe 4 we don't use them anymore preferring native HTML5 fields. This error sounds like it's being caused by some legacy code that should probably be removed. How would you feel about trying to remove it and making a pull request?

**Comment by robbieaverill** [comment] 2018-11-16 12:21
Pull requests at #380 and #381

**Comment by ScopeyNZ** [comment] 2019-01-09 02:37
PRs have been merged.

**Closed by ScopeyNZ** 2019-01-09 02:37 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/bug
